### ISSUE TITLE
Connection failure with Huawei MS2372h-517 Modem

### ISSUE THREAD

**Issue by Oliver1948** [uavpal/disco4g#103]
Hey everyone!
I have recently tried to use the 4g mod on my drone with a Huawei MS2372h-517 modem, but it doesn't want to connect. When I look in the ulogcat, the drone recognizes the modem, and then tries to identify it as Stick or Hi-link mode (Detecting Huawei Modem Type). That is the last message displayed about my modem, and nothing else happens. A few people have recommended installing new firmware on the modem, but I don't know where I would find new firmware, and I don't know how to do it, as my modem gives me no way to configure its settings. If anyone has any experience with this modem, I would greatly appreciate their advice.

Thanks in advance,
Oliver

![Capture](https://user-images.githubusercontent.com/93887543/141024008-c7ba4286-1b43-4282-9230-17d03042e6dc.JPG)

**Comment by s0ftice** [comment]
did you swap the 2 variables as advised here: https://uavpal.com/disco/faq#othermodems

:point_right: for the E3276s and MS2372h, you need to swap the values (0 and 1) of the variables serial_ctrl_dev and serial_ppp_dev in /data/ftp/uavpal/bin/uavpal_disco.sh.

**Comment by Oliver1948** [comment]
Yes I did, but nothing changed.

**Comment by s0ftice** [comment]
nothing happens after the last "detecting huawei modem type".
maybe you run `ulogcat |grep uavpal` to filter out the noise.

**Comment by Oliver1948** [comment]
I did what you said, but still the last thing that poped up regarding the modem was
I uavpal_drone(ulogger)                        : ... detecting Huawei modem

**Comment by Oliver1948** [comment]
Could I need new firmware?

**Comment by s0ftice** [comment]
Yes, I would probably try a different firmware then. Don't ask for links :)

**Comment by Oliver1948** [comment]
I found the solution! Buy a new modem ;)
