### ISSUE TITLE
Zerotier

### ISSUE THREAD

**Issue by hupka36** [uavpal/disco4g#106]
Hi, 
can i Please You to add one feature : site in another zerotier config file.

ZT i open source platform and anyone can make private ZT server on own HW (accessible via public domain or IP)
but zerotier-one client in disco and SC2 is compiled in binary and routed to only one - not changable server
 

Thank you 
WBR -s-

**Comment by s0ftice** [comment]
Most users get a direct connection between both zerotier peers, meaning it is not routed over any server. This is generally the goal when trying to get a low latency connection.

If you still want to set-up your own server, you can follow the gist here:
https://gist.github.com/s0ftice/491ad5cc99a69cba15bb884384670d43
(no need to change binaries!)
