### ISSUE TITLE
Issue glympse link

### ISSUE THREAD

**Issue by Fred06220** [uavpal/disco4g#110]
Hi, how are you? I'm Fred from France.
First of all, thank you for the job you've provided. You really did a good work. Thank you very much.
 well my problem is : the Install worked, but the link I receive from glympse, lead me to the internet site not to the app. Instead receiving https://glympse.com/06UY-JH5N (example),
I receive https://glympse.com. then I'm not able to track the parrot Disco because I'm redirecting to the main site of glympse where it provides ad about glympse but not the map.

I've checked all the process I had to do and I did the job well, but I can't receive the good glympse's link to track my Disco. my 4g key works perfectly and the disco's control finish to be connected to the Disco (blue light stay fix). Does anyone could help me please? 
I  attached file, I put a screen shot of pushbullet.

![Screenshot_20221215-011013](https://user-images.githubusercontent.com/40173943/207742407-dc1b04b4-b17e-47ef-a082-6a41de71b982.jpg)
 Thank you!
Fred.

**Comment by s0ftice** [comment]
Glympse should be working again in the latest beta (see details here: https://uavpal.com/disco/faq#beta). Or simply replace the uavpal_glympse.sh file using https://raw.githubusercontent.com/uavpal/disco4g/master/disco/uavpal/bin/uavpal_glympse.sh

**Comment by Fred06220** [comment]
Thank you very much. I'm gonna try it. I'll let you know if it works.
Thank you again
