### ISSUE TITLE
!HELP!  https://developer.glympse.com/account/create

### ISSUE THREAD

**Issue by DarionFlys** [uavpal/disco4g#114]
Since this link is now down..I'm not sure what to do. Can anyone offer me some up to date help or alternatives? I am eager to start my 4G mod 10 years late, but I am stuck at step 1.. Thanks!!

https://developer.glympse.com/account/create

**Comment by s0ftice** [comment]
Following screenshot taken from https://www.facebook.com/groups/173527569745090/permalink/1939831409781355/
You can reach out to Cami Zimmer to get an API key.

<img width="656" alt="image" src="https://github.com/user-attachments/assets/1131321c-277e-4dbb-b416-fd3c9bba7447">

keep in mind, Glympse is optional. You could also do the mod without it.

**Comment by DarionFlys** [comment]
Softice you are a real lifer saver thank you. I really just want to do the
mod and be able to have telemetry information. Thank you very much.
