### ISSUE TITLE
4g

### ISSUE THREAD

**Issue by rodbz22** [uavpal/disco4g#115]
Salut et merci de m'accueillir
Heureux possesseur d'un Parrot disco Je suis français en France
Je voudrais l'équiper de la 4G je cherche de l'aide pour acheter le matériel et surtout pour m'aider à configurer à installer
actuellement J'ai simplement un iPhone 8 et un ancien iPad Air wi-fi
J’utilise l’Internet par la 4G sur mon iPhone, et grâce a mon iPhone Je peux avoir Internet sur l’iPad.
Et surtout je vais respecter au maximum les autorisations en sachant que c'est interdit mais je vais quand même le faire.
Merci de bien vouloir m'aider 
Rodolphe

**Comment by s0ftice** [comment]
please join our Slack channel for help and support: https://uavpal.com/slack
The Github issues are to report bugs and issues :)

Thanks
