### ISSUE TITLE
SKC can not connect Disco via zerotier

### ISSUE THREAD

**Issue by stishsun** [uavpal/disco4g#13]
I have successful connect Zerotier both of Disco and SKC. the zeiotire shown both device in list.

I also can ping the peer IP address assigned by Zerotier from Disco.

but the SKC still flash blue not change to steady blue...

any idea?

**Comment by uavpal** [comment]
Most probably, because Ethernet Bridge is not enabled for **both** devices in Zerotier....?

**Comment by stishsun** [comment]
yes, you are right, finally I found the icon to bridge them

thank you

**Comment by uavpal** [comment]
Thanks. I added it to the FAQ:
https://uavpal.com/faq#blueflashing

Closing the issue now.

**Comment by stishsun** [comment]
this icon is "wrench", not "screwdriver", I looking fo "screwdriver" icon, not not found...

**Comment by uavpal** [comment]
lol, sorry. You're absolutely right! I just corrected the installation wiki and FAQ. Thanks!
