### ISSUE TITLE
problem with skycontroller 2 FW v1.0.3

### ISSUE THREAD

**Issue by ryangoldkey** [uavpal/disco4g#16]
Dears,

I'm havin' problems with the skycontroller 2 FW v.1.0.3.
I installed everything successful and the disco is already connecting to ZT with LTE. 
The problem I got is that my skycontroller is not connecting with my iPhone7. When I press the setting button two times nothing happens. 

Do you have any ideas? 

many thanks in advance and pls excuse my English :P

**Comment by ryangoldkey** [comment]
or do you guys know how to get skycontroller FM 1.0.7?

best rgdrs!

**Comment by ryangoldkey** [comment]
Hi Softice,

tried to update on 1.0.3 but no update available. 
![img_6323](https://user-images.githubusercontent.com/39911843/40934349-c8920488-6834-11e8-8460-66a23780b495.png)
![img_6322](https://user-images.githubusercontent.com/39911843/40934371-df107dfc-6834-11e8-85ad-1d02fd085e22.png)

**Comment by uavpal** [comment]
Some people on the Parrot Community Forum seem to have the same problem....

I know a way of force up-/downgrading SC2.
It‘s not very straight-forward though. Let me see if I can write somewhat simple instructions for it.

SoftIce

**Comment by uavpal** [comment]
Give it a try! https://github.com/uavpal/disco4g/wiki/Manual-firmware-upgrade-and-downgrade-of-Parrot-Skycontroller-2

I wrote these instructions from the top of my head, so it (most likely) will not work on first try. Let me know if any of the steps are not clear or gives you an error. I will update the wiki article based on your feedback.

**Comment by ryangoldkey** [comment]
Dear SoftIce,
pls take a look:
![image](https://user-images.githubusercontent.com/39911843/40956277-a39bacc8-688f-11e8-9036-a518c94a1985.png)

**Comment by ryangoldkey** [comment]
the sc got the IP address 192.168.42.12

**Comment by ryangoldkey** [comment]
Hi Softice,
gettin better..
![image](https://user-images.githubusercontent.com/39911843/40968075-f8cd99fc-68b4-11e8-9941-cd736c94035b.png)
![image](https://user-images.githubusercontent.com/39911843/40968076-f8e63480-68b4-11e8-8afb-37eed5b93e06.jpeg)

**Comment by uavpal** [comment]
refresh the instruction page and start over :) I updated at about the same time when you ran the commands, I found another mistake. It's not easy to write these without being able to try it out on my own SC2...

by the way, where does the question mark before /usr/bin/pinst_trigger 1 and reboot come from in your screenshot? that's not in the instructions...

**Comment by uavpal** [comment]
and there you need to hit Return between reboot and rm. you pasted both commands on the same line, but these are separate lines in the instructions!

**Comment by ryangoldkey** [comment]
the disco is rebooting after hitting return. do I need to connect again to past your last code line? 
rm /data/ftp/internal_000/adb.dms /data/ftp/internal_000/mpp_update.plf

best rgrds!

**Comment by uavpal** [comment]
why is the binary named adb.dms? did you rename it manually before uploading? should just be adb...

please let me know any changes you apply :) so I can make sure I update the instructions so others can do it too

**Comment by uavpal** [comment]
you need to start over

**Comment by ryangoldkey** [comment]
yeah I changed it course otherwise terminal doesn't find the file...
so just for understanding:
After rebooting im going to connect with telenet... to the drone and than I only need to pass the last code line and hit return/enter?

thanks

**Comment by uavpal** [comment]
No you need to do everything again.
This time line by line and not two lines at the same time.
And it seems you copied the bullet point as well for some commands which transformed into a preceding question mark. So the command couldnt run

**Comment by uavpal** [comment]
Weird... Why didnt terminal find the file if you dont rename? Can you send me a screenshot?
Thanks

**Comment by ryangoldkey** [comment]
![image](https://user-images.githubusercontent.com/39911843/40969964-88e016a6-68b9-11e8-9b68-0cf68fab0555.png)
![image](https://user-images.githubusercontent.com/39911843/40969977-8f62fcfa-68b9-11e8-806f-bb0f3e530889.png)

**Comment by ryangoldkey** [comment]
I can not copy the last line into the terminal because the disco reboots and loses connection

**Comment by ryangoldkey** [comment]
/data/ftp/internal_000/adb adb shell

/data/ftp/internal_000/adb.dms adb shell? like that right?

**Comment by ryangoldkey** [comment]
sry for being a noobie :P try my best

**Comment by ryangoldkey** [comment]
rm /data/ftp/internal_000/adb.dms /data/ftp/internal_000/mpp_update.plf

I need to attach the file endings

**Comment by uavpal** [comment]
Can you join us Slack? Easier: https://github.com/uavpal/disco4g/blob/master/README.md#contactcontribute

**Comment by uavpal** [comment]
The article
https://uavpal.com/wiki/Manual-firmware-upgrade-and-downgrade-of-Parrot-Skycontroller-2
is updated and should work. However, it did not work for @ryangoldkey, I assume his SC2 has a memory issue. Best to get it replaced by Parrot.

**Comment by uavpal** [comment]
The answer is very simple:

- Latest firmware for Skycontroller **2** (internal hardware identifier: 090f/mpp) is 1.0.7
- (build date: Oct 24 2017)
- Latest firmware for Skycontroller **2P** (internal hardware identifier: 0915/mpp2) is 1.0.3
- (build date: Jan 25 2018)

Distinguishing characteristic: the Skycontroller 2P has black joysticks.

In other words:

- SC2P with 1.0.3 is even newer than SC2 with 1.0.7.
- These are two different hardware platforms and the firmware files are not interchangable between SC2 and SC2P.
- The version 1.0.3 on SC2 is not comparable to version 1.0.3 on SC2P.

SoftIce
