### ISSUE TITLE
ZeroTier does not see the Disco or the SC2

### ISSUE THREAD

**Issue by richfriz** [uavpal/disco4g#17]
I am probably doing something stupid butt... I can get everything working except no devices show up on ZeroTeir. I have tried making new networks, changing the network id in the conf files and uploading again. I have done this about 5 times. On one occasion I did see the Disco but not the SC2 ?? The SC2 connects to the hotspot. The modem is working (solid cyan LED) I meticulously cut and paste the network id so there should be no mistake.  I also ran the "downgrade" mod. All to no avail 

![zt1](https://user-images.githubusercontent.com/17118694/40949202-85289dcc-689f-11e8-8c8c-f02621475d88.JPG)
![zt2](https://user-images.githubusercontent.com/17118694/40949204-8956a70e-689f-11e8-9546-78c4d6183022.JPG)

**Comment by uavpal** [comment]
can you telnet into your disco and tell us what `ulogcat |grep uavpal` returns?

**Comment by uavpal** [comment]
feel free to join us on slack (https://github.com/uavpal/disco4g/blob/master/README.md#contactcontribute) and PM me, so you don't have to post your logs all over the Internet :)

**Comment by richfriz** [comment]
All solved : Thank you for the fantastic support
