### ISSUE TITLE
mod not working correctly

### ISSUE THREAD

**Issue by arthur9711** [uavpal/disco4g#23]
Hi,

first thanks for everything.
But i have a big issue
at first all was working but since this morning nothing works.

i've tried uninstall and reinstall but the disco doesn't show a blue flashing led whereas the modem is correctly connected and showing a cyan led.

i don't know from where the problem come from.

the skycontr is showing a blue led and correctly connect to my iPhone.

on zerotier both are connected .

**Comment by arthur9711** [comment]
After the last uninstall i've made and nothing plugged into disco and skycontr the led on disco flash blue ...

**Comment by arthur9711** [comment]
@uavpal maybe you've already seen this issue ?

**Comment by uavpal** [comment]
I will close this issue if I don't hear back.
