### ISSUE TITLE
Latest Disco Firmware 

### ISSUE THREAD

**Issue by jcarlos68** [uavpal/disco4g#24]
Anyone tested the mode with latest firmware released ?

**Comment by LKNP** [comment]
I did. Needs a reinstall after updating the Disco, which works fine. I will test fly it later today.

**Comment by LKNP** [comment]
Test flight done. Worked like a charm.

**Comment by uavpal** [comment]
Thank you very much @LKNP for testing! yes it's working fine indeed. I added 1.7.1 to the supported firmware section on the main page. I will close the issue hereby.
SoftIce
