### ISSUE TITLE
ZeroTier connection

### ISSUE THREAD

**Issue by Thyristornp** [uavpal/disco4g#25]
Hello!

I did everything according to the instructions.
I have Authorize Disco and Skycontroller in ZeroTier, but always when I turn they on, I see only one member online, Disco or Skycontroller or nothing.
They connects only sometimes.
USB modem is OK and Skycontroller is connected to my phone via Wi-Fi.
Maybe it is IP blacklisting in Russia? How can I check this connection to ZeroTier? May be it is a command like a ping?

**Comment by uavpal** [comment]
you can run `/data/ftp/uavpal/bin/zerotier-one -q status` to check its status

**Comment by Thyristornp** [comment]
I have this message:

/ # /data/ftp/uavpal/bin/zerotier-one -q status
200 info 460e4f9dde 1.2.6 ONLINE

But, there is no connection in https://my.zerotier.com/network

**Comment by uavpal** [comment]
he status in the Web UI is not always accurate (however most of the time it is). Can you see an IPv4 address assigned to the members? Can they ping each other? Do you get steady blue LED on the controller?

**Comment by uavpal** [comment]
did you ever delete a member for a network ID in the zerotier UI?

Can you join the community on https://uavpal.com/slack and upload a screenshot of your zerotier account (network tab)?
Thanks,
SoftIce

**Comment by uavpal** [comment]
can I close this issue?

**Comment by ct1ftk** [comment]
I have already installed everything and configured it as described and I am almost giving up on this solution because I can not establish communication with "ZEROTIER" (between Disk and SC2). I have spent many hours in experiments and tests, I have spent too many hours of rest. I'm saturated!
Please, anybody can help me?
Thanks,
Henrique Manso

**Comment by ct1ftk** [comment]
See the screenshot in attach:
![zerotier2](https://user-images.githubusercontent.com/16966581/43049468-491f8040-8df0-11e8-8e04-e1d653e324b3.jpg)


![zerotier1](https://user-images.githubusercontent.com/16966581/43049451-0f23bda2-8df0-11e8-99c6-8d9f8e424fe1.jpg)
![zerotier3](https://user-images.githubusercontent.com/16966581/43049472-54f3dcf4-8df0-11e8-8d17-818e4ae5eb38.jpg)

**Comment by uavpal** [comment]
all resolved now? can I close this issue?

**Comment by s0ftice** [comment]
please ask on slack in #Disco4G for help

**Comment by mysaidi007** [comment]
Do you have the link?

**Comment by s0ftice** [comment]
https://uavpal.com/slack

**Comment by mysaidi007** [comment]
Already join found nothing

**Comment by mysaidi007** [comment]
Can you give me the link direct to the disco 4g issue

**Comment by s0ftice** [comment]
If you don't ask for help on Slack, people wouldn't know you need some :)

**Comment by kimkabsoo** [comment]
HI !
I have bebop2

Blue LED on the controller is blinking blue after connection to phone wifi, but I can't Authorize it

I have this telnet message:
/ # /data/ftp/uavpal/bin/zerotier-one -q status

/data/ftp/uavpal/bin/zerotier-one: missing port and zerotier-one.port not found in /var/lib/zerotier-one

**Comment by s0ftice** [comment]
Please join us on Slack for installation troubleshooting
