### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by biky83** [uavpal/disco4g#32]
Hello, 
I experiment very high latency (between 3-6sec) my ping on the phone is 60-70ms and on the 4g usb key 80 ms. The image is good. 
The latency is not only for the video but for the commands too

**Comment by uavpal** [comment]
probably, because your connection gets relayed via Internet. Check out the FAQ on typical scenarios when that is the case and how to check and confirm that it gets relayed.

**Comment by biky83** [comment]
Thanks 
My modem was on hilink mod 
I changed it to stick mod
The carrier is the same
Many thanks for this mod !
