### ISSUE TITLE
Problem tracking with Glympse

### ISSUE THREAD

**Issue by Killianre** [uavpal/disco4g#38]
Hello,
i have a problem with glympse: i receveid the sms but i only have https://glympse.com/ so i can't track the disco. Like one month i've got the number and the tracking works. A solution ?

**Comment by uavpal** [comment]
The link should look like https://glympse.com/abcd-efgh
If that's not there, usually because the Glympse API key is not or wrongly configured in the config file.
SoftIce

**Comment by Killianre** [comment]
i have reinstall the Glympse API key but the problem is always there

**Comment by uavpal** [comment]
do you mind sharing your glympse_apikey config file? you can send it via email to info@uavpal.com so it's not publicly visible for everyone.

**Comment by Killianre** [comment]
ok i send you the file

**Comment by johanjohn23** [comment]
Hi I am having the exact same problem! Can you please help me out with this as well?

Thanks,
Johan

**Comment by uavpal** [comment]
Yes, everyone was affected. It seems there was a server issue on Glympse's side. I received one report that it's working again. Can you try and let me know? I can't test it myself right now. Will open a ticket with Glympse.
Thanks

**Comment by pwrkiter** [comment]
Hi guys, same problem here. It was working last time I tried (15/08/2018) but today when I receive the pushbullet notification it is missing the usual 6 or 8 character link after the glympse.com and I only get:

DISCO-XXXXXX's GPS location: You can track the location of your DISCO-XXXXXX here: https://glympse.com/

Not sure if it's related but I had to re-enable the "Allow ethernet bridging" checkboxes on both devices on ZeroTier today as they had unchecked themselves.

**Comment by pwrkiter** [comment]
Just seen your latest post, I'll give it a try in the morning. Thanks!

**Comment by uavpal** [comment]
no, not related to zerotier at all...

**Comment by uavpal** [comment]
It's working again. It was a Glympse server issue, nothing much we could do about it apart from contacting their support. I'll close the ticket hereby.
SoftIce

**Comment by johanjohn23** [comment]
Thanks! Yeah it’s working for me again.

**Comment by skyer29** [comment]
Hi guys, 
I' m having the same problem.
The new glympse .sh file in BIN folder doesn't work.
How did you resolved this problem?

**Comment by s0ftice** [comment]
that was a different issue. what you are looking for is here: https://github.com/uavpal/disco4g/issues/88
