### ISSUE TITLE
skycontroller_install.sh returns flood: "Trying to connect to Skycontroller 2 via WiFi"

### ISSUE THREAD

**Issue by Mavleg** [uavpal/disco4g#44]
Hello.
I have successfully installed the softmod onto an exiting Disco-Skycontroller2 pair, and it works beautifully. I am currently trying to replicate the process with a second pair, and I have gotten as far as the telnet commands. After successfully telnet-ing to `192.168.42.1`, I used the command `/tmp/disco4g/skycontroller2/skycontroller2_install.sh`. The command prompt floods with the message `Trying to connect from Disco to Skycontroller 2 via WiFi`, printed tens of times per second. The installation procedure never starts.
Restarting the Disco and the Skycontroller2 had no effect. Both devices are using exactly the same firmware versions as the pair that worked for me earlier. My mobile device is unplugged from the Skycontroller2. A hard reset on the Disco and a complete re-FTP of the softmod did not fix the issue. The Skycontroller2 has a solid green LED, and is fresh out of the box.
Any thoughts?

**Comment by uavpal** [comment]
what does `ping $(netstat -nu |grep 9988 | head -1 | awk '{ print $5 }' | cut -d ':' -f 1)` return?

I suggest you join us on https://uavpal.com/slack

**Comment by s0ftice** [comment]
this is solved. user did not run the disco_install.sh script according to the instructions.
