### ISSUE TITLE
Skycontroller 2 doesn't work with WiFi home router.

### ISSUE THREAD

**Issue by tripmanPL** [uavpal/disco4g#47]
Skycontroller 2 work fine with mobile router but doesn't work with home router (with the same wi-fi settings).
Home router use internet from T-Mobile. Mobile router same as modem from disco use internet from Play (local Polish mobile operator).
I need use home router because of faster broadband but can't connect Skycontroller.
Is it possible that home router has some settings not allowing to get connection to Skycontroller?
Thanks for help.

**Comment by s0ftice** [comment]
Can I close this issue?
