### ISSUE TITLE
wifi connection problem

### ISSUE THREAD

**Issue by juliocaja** [uavpal/disco4g#48]
Hi, im not sure if this is the same person but im unfamiliar with this page so il post it just in case. In my disco the instalation was successful, but towards the end when I attempt to start my disco via 4g I am unable to get the orginal green light for that wifi connection. The modem has made it so I either connect via 4g and not wifi or vise versa. Any suggestions on how to fix this?

**Comment by Monomon1980** [comment]
Hi, the blue color by pressing the key twice (settings) would get 4G / LTE and if the color is green you will be connected to WiFi. If you want to go from one to another you have to press the key (settings), and it will change from one mode to another
