### ISSUE TITLE
SPEED

### ISSUE THREAD

**Issue by Monomon1980** [uavpal/disco4g#49]
Como aumentar la velocidad de la disco en modo automático. Al igual que se puede modificar los datos de batería, cuales serían los datos a modificar en caso de querer aumentar la velocidad de nuestro ala, así como intentar saber cual es el conector de la señal en nuestra Chuck para poder controlar un variador sin necesidad de utilizar el de la Chuck. No creo que sea difícil pero yo no tengo los medios. Seri para modo automático con todas las funciones. En modo manual si se puede...
How to increase the speed of the disk in automatic mode. As you can modify the battery data, what would be the data to modify if you want to increase the speed of our wing, as well as try to know which is the signal connector in our Chuck to control an inverter without having to use the Chuck's. I do not think it's difficult but I do not have the means. It will be for automatic mode with all functions. In manual mode if you can ...

**Comment by s0ftice** [comment]
Hi there, I'm closing this issue as it's not really a 4G softmod related.
I suggest you join our community at https://uavpal.com/slack, where you can post your question in #disco-general, you'll be much more likely getting an answer.

See ya there.
