### ISSUE TITLE
Parrot Skycontroller 2P Firmware version 1.0.3 upgrade to 1.0.5 issues

### ISSUE THREAD

**Issue by kb4zgo** [uavpal/disco4g#52]
I just purchased a new Skycontroller 2P which has version 1.0.3 and now an update has arrived 1.0.5 and I have tried several times to download it via Freeflight Pro and not able to get the download to update the firmware. Any suggestions on how to get the update or where to find the plf file for the Skycontroller 2P . 

I wished Parrot would get the website fixed to where you can get the file as in the past ..

**Comment by kb4zgo** [comment]
This is not related to the 4G softmod. I have read something that does make sense to me and that Parrot has created a working file for IOS devices but not Android; this seems to be the case in my opinion. It's my hope that software engineers or designers would soon create a working file to update the firmware for Skycontroller 2P v1.0.3 to v1.0.5 for Android users. I use Android devices for my telemetry video feed from the Parrot Bebop 2 drone and also Freeflight Pro app.  

Also it would be nice if the files would be accessible from a website such as Parrot once had before the website change.

Question: Will the URL given with mpp2 update  work with Android? 
https://firmware.parrot.com/Drones/0915/1.0.5/ALL/mpp2_update.tar.gz

I ask due to my recent purchase of a NEW Skycontroller 2P v1.0.3 in December 2018

Thank you ever so much for the URL link for the update file. I'll wait till I receive some answer to my inquiry.

**Comment by s0ftice** [comment]
Hey kb4zgo, I will close the issue as it's not softmod related.

You will need to find a PC-based process similar to https://github.com/uavpal/disco4g/wiki/Manual-firmware-upgrade-and-downgrade-of-Parrot-Skycontroller-2 which describes how to manually upgrade SC2. SC2P will be slightly different, as firmware updates are no longer distributed as .plf files (.tar.gz now). But I don't think you can do it manually via Android or iOS if the built-in upgrade capability does not work.

Easiest solution is possible to use/borrow an iOS device, install FFpro and do the one-time upgrade from there.

Feel free to join the community on https://uavpal.com/slack.

SoftIce
