### ISSUE TITLE
Can't connect to Disco via ftp 51 (port closed)...

### ISSUE THREAD

**Issue by Murgator** [uavpal/disco4g#56]
Hi ! I tried to install the 4G mod in my Parrot Disco 1.7.1 that I bought in January 2019 but I can not connect via port 51 or 21 with filezilla.

1) I establish a wifi connection between my PC and my Disco (Disco IP address is: 192.168.42.44), the connection is a success.
2) Then I try an ftp connection with filezilla at 192.168.42.44:51, but the connection is refused (closed port).

So I did a port scan with nmap and here's what I got:

![scan de port disco copie](https://user-images.githubusercontent.com/38978895/52912933-995eaa00-32b8-11e9-8195-ff841d011b6d.png)

So I tried to connect via ports 135, 139, 445 and 2968 but the connection seems to be awaiting authentication.

Can be a security update from Parrot ?

Evidently telnet does not work either.

Do you have a solution ?
Thank you in advance.
David

**Comment by s0ftice** [comment]
192.168.42.44 is probably your own (Windows PC’s) IP address. The Disco is always 192.168.42.1.
Just follow the instructions one by one, can’t really go wrong.

SoftIce

**Comment by Murgator** [comment]
Thank you for your response Softice the problem has fix, I simply start the process again...

But i have another problem with my 4h modem. I open a new ticket.
