### ISSUE TITLE
My E3372s - 153 4G Modem can't connect, zerotier member not created.

### ISSUE THREAD

**Issue by Murgator** [uavpal/disco4g#57]
Hi ! I followed all the installation steps of 4G 1.2 mod successfully and when I typed REBOOT in TELNET console the disco restarted.

The Huawei E3372s - 153 does not connect (flashing green led for several minutes).

So I plugged the key into my computer and disabled pin code protection and enable automatic login.

I manually restarted the disco with the Huawei E3372s.

The led of the Huawei E3372s has become blue fixed, so it is connected to the internet but the disco does not connect to zerotier (no member is created).

Here is the firmware version of the Huawei E3372s 4G key:

![sfr](https://user-images.githubusercontent.com/38978895/52916737-a47aff80-32e3-11e9-95de-95a86fa747c5.png)

An idea ?
Thank you in advance
David.

**Comment by s0ftice** [comment]
Can you send us the output of the log on the disco? See details here: https://uavpal.com/disco/faq#discodebug

I suggest you join us on Slack: https;//uavpal.com/slack
You'll have an entire community to help and troubleshoot your setup :)

Thanks,
SoftIce

**Comment by Murgator** [comment]
here is my logs:

![15dad4aafdc71623f82c4ed34fc64a80](https://user-images.githubusercontent.com/38978895/52968153-a5c42f00-33ac-11e9-8099-2cfd2781a3a8.png)

I tested with 1.1 mod and it's work, but not with 1.2....

Ok thank you i will join the community

**Comment by krwi** [comment]
Same here, repeated modem disconnects, no ZT connection, no Glympse notification.
Hilink E3372, worked like a charm in disco4g v1.0.

**Comment by Murgator** [comment]
Fixed by changing modem to a e3372h 153 and create another zerotier networf

**Comment by JeanVautrin** [comment]
Hi Murgator
I am considering the Disco4G softmod. I received the E3372h - 153.
Now I hesitate choosing the mobile 4G provider.
I plan to get 2 40Go/50Go sim cards sans engagement.
Would you advise RED/SFR or Sosh/Orange?
Cordially

**Comment by s0ftice** [comment]
@JeanVautrin I recommend you join us on Slack: https://uavpal.com/slack, you can reach out to our French members there.
SoftIce

**Comment by Murgator** [comment]
JeanVautrin j'ai pris cet abonnement SFR 4G à 3€ par jour d'utilisation car je ne voulais pas payer un abonnement mensuel: https://www.sfr.fr/box-internet/internet-partout.html

**Comment by JeanVautrin** [comment]
Merci Murgator

Merci pour ta réponse. Très bonne info mais SFR semble très mal couvrir 4G mon village et j’ai peur d’avoir du mal à faire les mises au point.
Comme je l’ai dit sur UAVPAL (alias jyvai) j’envisage Sosh Orange.

A+


________________________________
De : Murgator <notifications@github.com>
Envoyé : Sunday, March 3, 2019 3:27:25 PM
À : uavpal/disco4g
Cc : Jean Vautrin; Mention
Objet : Re: [uavpal/disco4g] My E3372s - 153 4G Modem can't connect, zerotier member not created. (#57)


JeanVautrin j'ai pris cet abonnement SFR 4G à 3€ par jour d'utilisation car je ne voulais pas payer un abonnement mensuel: https://www.sfr.fr/box-internet/internet-partout.html

**Comment by 1019144701** [comment]
E3372s - 153 and E3372h - 607 can't connect , now I will buy  a E3372h - 153 for a try.
