### ISSUE TITLE
Is it possible to control the drone completely autonomous?

### ISSUE THREAD

**Issue by zesanriky** [uavpal/disco4g#62]
I am really excited about this project. I have done autonomous AR drone 2.0 which flies completely autonomous without any remote control from the ground, rather running script from the laptop. Can I use this project the same way? 

Can I integrate open CV to it as well?

**Comment by s0ftice** [comment]
Not sure if I understand you correctly. Why do you need to combine complete autonomy with a 4G connection? For autonomy, you won't need a connection at all...?

**Comment by zesanriky** [comment]
Thanks for the answer. I just want to know is it possible to control it by any script from repository or I must use the joystick to control it manually? I understood it returns back autonomously only.

**Comment by s0ftice** [comment]
It can fly autonomously. There is even an integrated Flight Plan feature, where you can design a flight plan on a phone/tablet and send it to the drone. It will continue the plan upon losing connection.
These plans are just simple JSON files with coordinates which can be generated with the right tools as well.
