### ISSUE TITLE
Had to swap the serial_ctrl and serial_ppp params to get it to connect

### ISSUE THREAD

**Issue by arun4444** [uavpal/disco4g#63]
I am using a Parrot Disco with 1.7.1 firmware loaded. 
T-Mobile LTE
HUAWEI MS2372h-517

In order to get the drone to connect via 4g, i had to swap these variables:
serial_ctrl_dev="ttyUSB0"
serial_ppp_dev="ttyUSB1"

to

serial_ctrl_dev="ttyUSB1"
serial_ppp_dev="ttyUSB0"

with the original config, the script was stuck at 
... connecting modem to Internet (ppp)

**Comment by s0ftice** [comment]
Yep, that’s known and documented here
https://uavpal.com/disco/faq#othermodems

Thanks
