### ISSUE TITLE
Sky Controller never shows up on zero tier

### ISSUE THREAD

**Issue by jimschuler3** [uavpal/disco4g#69]

**Comment by jimschuler3** [comment]
I double press settings button 
i first upgraded to 1.7.1 disco connects to ZT but don't see SC
so i downgrade firmware to 1.4.1 same issue 
i double press disco to activate ZT still nothing
using Huawei e3372h 510
tmobile sim 
apn 
epc.tmobile.com
im in the U.S.
Does it have to be the same apn on my tmoble iphoneX
i looked on the usb modem and it said epc.tmobile.com so thats what i put in the bin file
any help would be appreciated

**Comment by jimschuler3** [comment]
i just removed my ZT network and started a new one  ....reinstalled softmod with newZT# and its the same thing

**Comment by s0ftice** [comment]
what color is the LED of your Skycontroller 2? Flashing masgenta and then going back to green? What hotspot device are you using?

**Comment by jimschuler3** [comment]
iphone x and yes flashing megenta then yellow then red then green

**Comment by s0ftice** [comment]
have a look here: https://uavpal.com/disco/faq#wififail

**Comment by tuttoto** [comment]
> iphone x and yes flashing megenta then yellow then red then green

I managed to connect with my iPhone 8,  but I had to rename it (I used my surname instead of “surname’s iPhone”...). I have only checked that I had video and steady blue light and headtracking, but I have not tried it in flight.

**Comment by jimschuler3** [comment]
just tried that in itunes but  it just says jims iphonex    not "jims iphonex"
im stumped

**Comment by jimschuler3** [comment]
ill change the name to just a single word maybe?

**Comment by jimschuler3** [comment]
heres a video of what its doing

https://www.youtube.com/watch?v=22Xh8GarCJU&feature=youtu.be

**Comment by s0ftice** [comment]
You can try, but you also should ensure that the config file on SC2 gets updated, e.g. via reinstalling the mod.
Can you attach a screenshot of your iPhone's name? Settings -> General -> About -> Name, as well as the current conf/ssid file?

**Comment by youness103** [comment]
Bonjour je suis dans le même cas de figure, j'ai beau essayer de recommencer la procédure le disco ce connecté bien mais la SC n'apparaît pas ça clignote bleu 🔵 après ça passe au vert 🌳je suis avec les derniers Version de mise à jour

**Comment by jimschuler3** [comment]
Photos of my settings
![57DE3565-9AE5-4588-9B80-9039E649F419](https://user-images.githubusercontent.com/58006293/69479617-4d9fda80-0dcd-11ea-9b9b-fcc657b85628.jpeg)
![2104D48F-2772-43F4-BED4-18633EE06E19](https://user-images.githubusercontent.com/58006293/69479618-4e387100-0dcd-11ea-96c3-421fdffbded2.jpeg)

**Comment by tuttoto** [comment]
> Photos of my settings
> ![57DE3565-9AE5-4588-9B80-9039E649F419](https://user-images.githubusercontent.com/58006293/69479617-4d9fda80-0dcd-11ea-9b9b-fcc657b85628.jpeg)
> ![2104D48F-2772-43F4-BED4-18633EE06E19](https://user-images.githubusercontent.com/58006293/69479618-4e387100-0dcd-11ea-96c3-421fdffbded2.jpeg)

It would be interesting to have the copy of the configuration file you loaded in the Disco for the Skycontroller...

**Comment by jimschuler3** [comment]
![A6A9A394-2E8F-4A4D-B292-2C43616CE0DA](https://user-images.githubusercontent.com/58006293/69485668-b2c8ef80-0e10-11ea-877f-6b95ab4f5c9a.jpeg)
Says  it loaded

**Comment by tuttoto** [comment]
I tried with my iPhone 8xl/256gb ios13.1.3... and this time it stays magenta for ever... then I tried to connect with an other phone on the hotspot, and discovered it wasn’t working for it also... I even entered the ssid/password manually (ssid was not even displayed on the list of available networks...) but it didn’t work either...
At some point, I disabled the authorization for non-iCloud users to connect to the hotspot, then enabled it again, which triggered an odd message requesting my approval to enable WiFi for users to connect to the hotspot... I pressed “ok” then my other phone was able to see the ssid and to connect to the hotspot, then after having switched the Skycontroller2 to WiFi and back to 4g mode... after ages... magenta turned blinking blue, then solid blue... video stream was s..t (I think I’m on reduced data rate on this data plan), but strangely glimpse reported direct connection and <>50ms latencies (not same apn as the Disco, though...). I think apple fucked the hotspot somehow... as I have not at all such weird behavior with my old Samsung s6 edge+... when I start the hotspot on the Samsung, the magenta light start blinking blue after seconds, then solid blue , then video stream a few seconds later...
I was not too confident about my iPhone (as I have to restart the WiFi many times during a single evening while watching YouTube (it looks like I’m connected to my home WiFi... but streaming is stopped, until I switch WiFi off/on)), then I never used it to actually fly my disco... I think I will not use it for 4g either. (Or maybe like Dustin Dunnil... he uses an Android phone for the hotspot and an iPad for FreeFlight/Auriga).
I hope it helped... if other users could share their point of view about iPhone/hotspots I would be interested.

**Comment by s0ftice** [comment]
> ![A6A9A394-2E8F-4A4D-B292-2C43616CE0DA](https://user-images.githubusercontent.com/58006293/69485668-b2c8ef80-0e10-11ea-877f-6b95ab4f5c9a.jpeg)
> Says it loaded

yeah, but I can't see what the conf/ssid file is currently set to on your screenshots

**Comment by s0ftice** [comment]
> I hope it helped... if other users could share their point of view about iPhone/hotspots I would be interested.

Least issues with iOS devices as long as users follow the two tips here https://github.com/uavpal/disco4g/wiki/faq#wififail

**Comment by jimschuler3** [comment]
Ok i may try to scrap the whole idea of using my iphone 
i see people using there home wifi  is that possible and what do i use as the apn is that going to also be the name of my network

**Comment by jimschuler3** [comment]
> I tried with my iPhone 8xl/256gb ios13.1.3... and this time it stays magenta for ever... then I tried to connect with an other phone on the hotspot, and discovered it wasn’t working for it also... I even entered the ssid/password manually (ssid was not even displayed on the list of available networks...) but it didn’t work either...
> At some point, I disabled the authorization for non-iCloud users to connect to the hotspot, then enabled it again, which triggered an odd message requesting my approval to enable WiFi for users to connect to the hotspot... I pressed “ok” then my other phone was able to see the ssid and to connect to the hotspot, then after having switched the Skycontroller2 to WiFi and back to 4g mode... after ages... magenta turned blinking blue, then solid blue... video stream was s..t (I think I’m on reduced data rate on this data plan), but strangely glimpse reported direct connection and <>50ms latencies (not same apn as the Disco, though...). I think apple fucked the hotspot somehow... as I have not at all such weird behavior with my old Samsung s6 edge+... when I start the hotspot on the Samsung, the magenta light start blinking blue after seconds, then solid blue , then video stream a few seconds later...
> I was not too confident about my iPhone (as I have to restart the WiFi many times during a single evening while watching YouTube (it looks like I’m connected to my home WiFi... but streaming is stopped, until I switch WiFi off/on)), then I never used it to actually fly my disco... I think I will not use it for 4g either. (Or maybe like Dustin Dunnil... he uses an Android phone for the hotspot and an iPad for FreeFlight/Auriga).
> I hope it helped... if other users could share their point of view about iPhone/hotspots I would be interested.

were do i turn that(authorization for non-iCloud) on and off

**Comment by tuttoto** [comment]
> were do i turn that(authorization for non-iCloud) on and off

It is the toggle just above the password field (in the hotspot parameters). To be precise, I switch off WiFi on the control center (when you slide up from the bottom of the screen, where there are sliders for volume, the light, etc) and then also in the parameters (as it is still ON after having put it OFF on the control center... ), THEN I put ON the non-iCloud users authorization toggle in the hotspot menu, which triggers a pop-up box requiring activation of the WiFi, I tap on it... it seems to reset properly the hotspot enough for the Skycontroller2 to connect on it...

**Comment by s0ftice** [comment]
> were do i turn that(authorization for non-iCloud) on and off

All you need to do is "Allow Others to Join" under Settings -> Personal Hotspot

**Comment by s0ftice** [comment]
> Ok i may try to scrap the whole idea of using my iphone
> i see people using there home wifi is that possible and what do i use as the apn is that going to also be the name of my network

iPhone is no issue, trust me. You can use the Home Wifi, but I strongly suggest to get it to work on your phone first. Ping me on Slack when you're online. I will run you through a set of commands to find out what is currently configured on your SC2.

APN does not change if you want to use Home Wi-Fi, as the APN is set on the Disco.

**Comment by youness103** [comment]
aide moi 
mon probleme est que une fois la connexion partage depuis mon pocophone le SC2 ne ce connect pas:
"aucune appareille connecté" sur ZEROTIER le disco est en ligne:
le SC2 est dificilement connectable question ; existe il un moyen de connecte la SC2 par cable USB au reseau ???????
