### ISSUE TITLE
4g no funciona

### ISSUE THREAD

**Issue by Pepo234** [uavpal/disco4g#73]
Hola, como estáis? Saludos a todos los que ayudáis aquí antes que nada. Mi problema es que mi módem Huawei e3372h-153 no conecta con el disco. No se que hacer, no encuentro más opciones. El skycontroller enlaza perfectamente con zerotier pero el disco no enlaza con mi módem. Que opciones tengo? Estoy buscando aquí información de todo tipo pero no he conseguido solucionar este problema. He intentado muchas muchas veces pero no he conseguido nada. Alguien puede ayudar? Muchas gracias.
Hi, how are you?  Greetings to all of you who help here before anything else.  My problem is that my Huawei e3372h-153 modem is not connecting to the disk.  I don't know what to do, I can't find any other options.  The skycontroller links perfectly to zerotier but the disk does not link to my modem.  What are my options?  I am looking for information of all kinds here but I have not been able to solve this problem.  He tried many times but got nothing.  Can anyone help?  Thank you very much.

**Comment by Pepo234** [comment]
![1586694905059973960239193169403](https://user-images.githubusercontent.com/54687535/79068985-a4e21100-7cc2-11ea-89d7-046d1acf0a92.jpg)

**Comment by s0ftice** [comment]
if the modem's LED does not light up at all (not even flashing), you are probably just using a charging cable without data wires. You need a USB **OTG** cable.

**Comment by Pepo234** [comment]
Si enciende pero siempre intermitente. Todas las veces que intento esta intermitente.

**Comment by Pepo234** [comment]
> Si el LED del módem no se enciende (ni siquiera parpadea), probablemente solo esté utilizando un cable de carga sin cables de datos. Necesita un cable USB **OTG** .

If it turns on but always flashing.  Every time I try it is flashing.

**Comment by ClassAxion** [comment]
Connect the modem to PC/laptop and check if it's working and connecting to the network properly.

**Comment by Pepo234** [comment]
> Conecte el módem a la PC / computadora portátil y compruebe si funciona y si se conecta a la red correctamente.

Yes, connected is ok in the pc, don't have problems with pc but in disco I can't.

**Comment by s0ftice** [comment]
telnet to your Disco and run `ulogcat |grep uavpal` after the modem has been plugged in for a minute or two. What is the output?

**Comment by Pepo234** [comment]
> Telnet a su Disco y ejecutar `ulogcat |grep uavpal`después de que el módem se ha conectado durante un minuto o dos. ¿Cuál es el resultado?

Could you explain this to me?  When I do it?  At what point do I have to do it?

**Comment by s0ftice** [comment]
Plug the modem into your Disco, turn it on, wait maybe 2 minutes, double press the Disco’s power button to enable telnet, telnet to your Disco, run the command, post the output here.

**Comment by Pepo234** [comment]
![15867054446071782234529521057974](https://user-images.githubusercontent.com/54687535/79072837-2b0a5180-7cdb-11ea-9866-93f6faf23724.jpg)

**Comment by s0ftice** [comment]
Have you installed the softmod?

**Comment by s0ftice** [comment]
Please run the command `dmesg` what are the last 50 lines?

**Comment by Pepo234** [comment]
> Ejecute el comando `dmesg`¿Cuáles son las últimas 50 líneas?

![15867071308363173323335701695784](https://user-images.githubusercontent.com/54687535/79073534-19c34400-7cdf-11ea-9e97-eeab72f17813.jpg)

**Comment by Pepo234** [comment]
> Ejecute el comando `dmesg`¿Cuáles son las últimas 50 líneas?

**Comment by Pepo234** [comment]
> > Ejecute el comando `dmesg`¿Qué son son las últimas 50 líneas?

![158670782463987346654320878343](https://user-images.githubusercontent.com/54687535/79073846-b63a1600-7ce0-11ea-9ba4-a7d9d0a867d6.jpg)

**Comment by s0ftice** [comment]
please try a different cable
