### ISSUE TITLE
 Skyontroler 2 sticks don't work

### ISSUE THREAD

**Issue by arturito00** [uavpal/disco4g#78]
After installing sofmod 4 G My Disc does not respond to skycontroles 2 sticks

**Comment by s0ftice** [comment]
When flying?

**Comment by arturito00** [comment]
Yes, Later testing in on the ground activating takeoff stabilization work but does not respond to sticks

**Comment by s0ftice** [comment]
Sticks won’t work on the ground either over Wifi

**Comment by arturito00** [comment]
No

**Comment by s0ftice** [comment]
Wasn't a question, I'm telling you. It's by (Parrot) design, so that's not a good way of testing the sticks.

**Comment by arturito00** [comment]
Thanks for the help.
I have discovered a fault in one of the servos that seems to be the source of the problem

**Comment by s0ftice** [comment]
Cool, I close it then
