### ISSUE TITLE
disco4g

### ISSUE THREAD

**Issue by donato11320** [uavpal/disco4g#81]
chi mi aiuta perchè non riesco a collegarmi con il disco parrot a zerotier non riesco a vedere nuovo utente o messo id
![disco](https://user-images.githubusercontent.com/69329726/89595626-4c2c1a80-d855-11ea-9296-2b804af78697.jpg)
 di 16 cifre fatto tutto come nella guida la kiavetta si connette ed diventa blu lo Skycontroller 2 si connette a zerotier e lo vedo ma il disco no

**Comment by djoris** [comment]
I don't speak Italian. Non parlo italiano.
Can you verify you have an internet connection from your Disco? Do you get a message on Pushbullet?
If you join https://uavpal.slack.com/ we might be able to help you faster.

**Comment by donato11320** [comment]
because i can't connect with the parrot disk to zerotier i can't see new user or put id of 16 digits done everything as in the guide that is in the drescizione the kiavetta connects and turns blue the Skycontroller 2 connects to zerotier and I see but the disco does not want to know or loaded the softcam 5 times but nothing where am I wrong friend can you help me thanks

________________________________
Da: Joris Dirks <notifications@github.com>
Inviato: domenica 9 agosto 2020 20:12
A: uavpal/disco4g <disco4g@noreply.github.com>
Cc: donato11320 <donatomarra@hotmail.it>; Author <author@noreply.github.com>
Oggetto: Re: [uavpal/disco4g] disco4g (#81)


I don't speak Italian. Non parlo italiano.
Can you verify you have an internet connection from your Disco? Do you get a message on Pushbullet?
If you join https://uavpal.slack.com/ we might be able to help you faster.

**Comment by donato11320** [comment]
![comando](https://user-images.githubusercontent.com/69329726/89739968-7106d480-da85-11ea-8295-d50b15822b90.jpg)

**Comment by donato11320** [comment]
no I do not receive messages but the modem the parrot disk key is light blue if I put it in the pc it maybe connects and an error of the softmod that does not connect is making me lose my head the skycontroller 2 I see it on zerotier but the parrot disk does not he wants to know to connect

**Comment by s0ftice** [comment]
did you get it to work?

**Comment by OpenUAS** [comment]
As the issue description is also a bit on the undiscriptive side( "disco4g"), and no response for a while, maybe close the issue?( that is technically not even a software issue for this issue tracker.)

@donato11320 Hai ancora qualche ultima parola?
