### ISSUE TITLE
Parrot Disco doesn't connect with ZeroTier 

### ISSUE THREAD

**Issue by Jon290501** [uavpal/disco4g#83]
Hello 
The Parrot Disco doesn't connect with ZeroTier after the Reboot on CMD. 
Modem --> E3372H-153 
There is NO Password on the Stick.
Installation on the Skycontroller 2 had work. 
The Skycontroller is visible on ZeroTier.

**Comment by s0ftice** [comment]
can u send a photo of your modem without the front cover? (slide it aside)

**Comment by Jon290501** [comment]
Hello 
The Problem was, that they send me the false version of the Huawei E3372....
Thank you for the quick answer and have a nice day ;) 

![Bruh moment](https://user-images.githubusercontent.com/71606120/93733209-c978d800-fbd4-11ea-8b4e-5ab8b27cacfa.jpeg)

**Comment by s0ftice** [comment]
Yeah, that's what I thought. I updated the docs today that the 320 model won't work. You are not the first one unfortunately.
