### ISSUE TITLE
Camera Only Connects When Using Wifi

### ISSUE THREAD

**Issue by jameslarson4thewin** [uavpal/disco4g#85]
Hey ive completed all the steps for the mod, but seem to have an issue with getting the camera to connect when using 4g.  If i switch to wifi, the camera view shows up again in the freeflight app.  When i am in 4g, i get a grey screen.  Everything else appears to be working as it should with the mod.  If i push the button to take a snap shot or video, it does it, but i cannot see the pictures on the disco memory until i go back to wifi.  Then i can see the files.  If i try to see the files while in 4g mode, it says" Impossible to connect to device" with an red error message.
The light on the drone blinks blue, and the light on the controller is solid blue.  
Uploading some screenshots...(the third picture with the error message is in the 4g mode)
![InkedScreenshot_20201106_170520_com parrot freeflight3_LI](https://user-images.githubusercontent.com/74080059/98425591-ef5a1f00-2052-11eb-9915-9f20a54401f6.jpg)
![InkedScreenshot_20201106_170525_com parrot freeflight3_LI](https://user-images.githubusercontent.com/74080059/98425594-f1bc7900-2052-11eb-98d9-30e45883fddd.jpg)
![Screenshot_20201106_170444_com parrot freeflight3](https://user-images.githubusercontent.com/74080059/98425599-f5e89680-2052-11eb-9428-16b972334c19.jpg)
![InkedScreenshot_20201106_170421_com parrot freeflight3_LI](https://user-images.githubusercontent.com/74080059/98425601-f8e38700-2052-11eb-932c-d9276f08348c.jpg)

Any suggestions would be really great as to what i should do, because i have tried changing the camera settings a bit and nothing has fixed it so far...

Thank you.

**Comment by s0ftice** [comment]
I believe you don't have sufficient bandwidth for the video stream. I suggest you do the two speed tests as advised here: https://uavpal.com/disco/faq#badconnection

**Comment by jameslarson4thewin** [comment]
Thank you for the reply.  I do believe you are correct.  My Tmobile data is
awfully slow.  I am going to use two mint-mobile sim cards which i have
ordered.  This is all good news because its easily fixed.  And by the way,
you are a fucking legend for figuring this shit out and making these
tutorials which are so easy to follow.

**Comment by s0ftice** [comment]
Thanks man :)

**Comment by OpenUAS** [comment]
Close it? Since the FAQ already has advise to fix this ...kindly asked ;)
