### ISSUE TITLE
ZTE modem compatibility

### ISSUE THREAD

**Issue by JurajHC** [uavpal/disco4g#86]
Hi!
Does anyone use ZTE MF79U modem?
I found that this user uses ZTE modem and it works, so I'm wondering if this one might be set up https://github.com/uavpal/disco4g/issues/9#issuecomment-388628140

I plugged it in but it doesn't seem to work. I don't see it listed with ifconfig command or listed anywhere under /dev/tty*
I can see it's connected to usb with lsusb
Any ideas how I can make this modem work? Are there any additional drivers I could try to install?
Thanks

**Comment by s0ftice** [comment]
you might get it to work, but will probably need to compile kernel drivers for it. there will also be changes required to the uavpal scripts to make it work.
