### ISSUE TITLE
Glympse

### ISSUE THREAD

**Issue by bato2000** [uavpal/disco4g#88]
Hi, I'm Ivan from SpainThank you very much for the work with the 4g mod of the parrot disco.
I have noticed a problem with glympse. 
It does not give a link to track the drone, it only gives the glympse page
Many thanks for everything

![IMG_7570F161B7F9-1](https://user-images.githubusercontent.com/61590944/112824296-a8fd6f00-908a-11eb-97c7-43418d0f921a.jpeg)

**Comment by s0ftice** [comment]
Hi, it's a known issue caused by Glympse, it hasn't been working for about 4 weeks. We informed them but no reaction so far.

Same thing happened about a year ago. Took them two weeks to fix it...

**Comment by bato2000** [comment]
thanks

**Comment by s0ftice** [comment]
Glympse should be working again in the latest beta (see details here: https://uavpal.com/disco/faq#beta). Or simply replace the uavpal_glympse.sh file using https://raw.githubusercontent.com/uavpal/disco4g/master/disco/uavpal/bin/uavpal_glympse.sh

**Comment by skyer29** [comment]
> Glympse should be working again in the latest beta (see details here: https://uavpal.com/disco/faq#beta). Or simply replace the uavpal_glympse.sh file using https://raw.githubusercontent.com/uavpal/disco4g/master/disco/uavpal/bin/uavpal_glympse.sh
I tried to replace glympse.sh file in BIN folder by filezilla but doesn’t work.

**Comment by s0ftice** [comment]
can you elaborate on "filezilla doesn't work"? what part of filezilla does not work? can you send some screenshots?

**Comment by skyer29** [comment]
no, filezilla works fine.
I changed the glympse.sh file in BIN folder using filezilla.
I have to do other things?

Il giorno mer 10 nov 2021 alle 13:01 SoftIce ***@***.***> ha
scritto:

**Comment by s0ftice** [comment]
you can run `ulogcat |grep uavpal` 1 or 2 minutes after the modem goes online and send me the output here.

**Comment by andresfg1** [comment]
![image](https://user-images.githubusercontent.com/94879063/142959042-2993d711-f577-4913-a748-c2dac9bdaac5.png)

**Comment by s0ftice** [comment]
you have not set a API key in the glympse config file...

**Comment by andresfg1** [comment]
Right, it was my fault, I'm going to do the test correctly.

**Comment by andresfg1** [comment]
thanks, using the latest beta version, glympse messages work fine

![image](https://user-images.githubusercontent.com/94879063/142961619-2b8aab47-cb68-4c64-b5a0-9f64caa58816.png)

**Comment by skyer29** [comment]
after numerous attempts to install and remove I finally solved the glympse problem.  I installed the latest version of the softmod and then I overwrote the glympse.sh file taken from the beta version of bebop2. So it works good.

**Comment by joaquinfranco1** [comment]
Right now I try to go to Glympse https://developer.glympse.com/ , and I cannot sign in into the Glympse, and I cannot get the link.

If I go to register my app: https://developer.glympse.com/account/create its a error 404 in the website. 


does anyone knows how to get the link code now? Thanks.

**Comment by joaquinfranco1** [comment]
![Image](https://github.com/user-attachments/assets/4c219341-76a3-4d37-9af7-19be794c6cfe)

I cannot get the Glympse link key:

![Image](https://github.com/user-attachments/assets/aaeae6ed-8b3e-4e46-9b39-791d41d2df96)
![Image](https://github.com/user-attachments/assets/8264772f-2fc4-4ae1-8300-898ace69c060)
![Image](https://github.com/user-attachments/assets/dd449090-9dbb-4bea-acbc-66a6acc2784a)

**Comment by s0ftice** [comment]
please see here https://github.com/uavpal/disco4g/issues/114 how to manually request for an API key from Glympse.
