### ISSUE TITLE
Modems

### ISSUE THREAD

**Issue by nemesis668** [uavpal/disco4g#9]
Hey buddy, Lots of people asking in UK which modem is right me included, Would rather not have to order from china and wait a month :)

Does this modem seem to be the correct one?

https://www.amazon.co.uk/gp/product/B07BNRZH3T/ref=ox_sc_act_title_1?smid=A1DWT37M9SCX7N&psc=1

**Comment by dailyknowmore** [comment]
I use ZTE mf825C, the configuation is easier than huawei 3372.  Just setting the  route and dns server ,the CHUNCK can surf  internet.
I think ZTE mf823, ZTE mf831 should work in the same way

**Comment by uavpal** [comment]
The Amazon link does not specify the type (H vs. S) and the model number (e.g. 153, 210, 510, 607).
You probably want to buy a E3372s-153 for the UK.
You can try ebay if shipping from China is not an option.

**Comment by sami31770** [comment]
Hello uvapal can you please explain on a video step by step how you connect the modem and the disco with windows please and how to transfer the file to the disco please

**Comment by sami31770** [comment]
i recently buy huawei E3372h-607 do it work in europe

**Comment by uavpal** [comment]
please see https://github.com/uavpal/disco4g/wiki/FAQ#e3372models
