### ISSUE TITLE
Glympse incomplete GPS tracking link

### ISSUE THREAD

**Issue by wangxiaoming1986** [uavpal/disco4g#90]
I am running the latest softmod on a Bebop2 & SC2 both updated to the last versions. Everything is running perfect with the exception of the Glympse link that comes empty with just the website link "https://glympse.com" and nothing after it. I checked, and double checked, and the API key is copied correctly from Glympse's website to the Bebop2's conf file.

Has anybody experienced this issue, or has anybody any other idea about what I could try to make Glympse work again?

**Comment by s0ftice** [comment]
Yes
See https://github.com/uavpal/disco4g/issues/88
