### ISSUE TITLE
Glympse Link + question

### ISSUE THREAD

**Issue by xerocomus** [uavpal/disco4g#91]
Dear guys,

I am sorry but I do not understand how to solve this glimpse link issue.  I see this was disscussed allready (#88, 89 and 90), there seems to be a solution available, but I do not understand it. 

More precisely, could someone please explain this to me (quote from #88):
"or simply replace the uavpal_glympse.sh file using https://raw.githubusercontent.com/uavpal/disco4g/master/disco/uavpal/bin/uavpal_glympse.sh"

And since I am allready here, I wanted to ask:
I would like to change the mobile operator for both sim cards. Would I need to re-install the softmod if both phone numbers remain unchanged (but new mobile operator)?

Thanks a lot
Martin

**Comment by s0ftice** [comment]
you download the file using your browser and replace the same file in the disco4g folder you have on your computer. then transfer it using an FTP client such as FileZilla. If you need more info, please check on Slack.

I answered the SIM card question on Slack just now.
