### ISSUE TITLE
Parrot Disco - RTH error, automatic landing but no return home.

### ISSUE THREAD

**Issue by Robifpv20** [uavpal/disco4g#93]
Parrot Disco - błąd RTH, automatyczne lądowanie lecz bez powrotu do domu... Witajcie panowie i panie i wszyscy miłośnicy podniebnych lotów Parrot Disco. Dużo godzin mam przelatane lecz głównie na oryginalnym wi-fi, a tylko parę na LTE.  I właśnie kilka dni temu spotkało mnie to czego obawia się każdy pilot drona. Dron przestał reagować, przestał wykonywać polecenia i sam zaczął lądować ruchem okrężnym, ale uwaga: nie w domu, nie w miejscu startu, lecz 200 metrów ode mnie. Straciłem kontrolę nad nim 200 metrów ode mnie i włączył sobie sam  obniżanie lotu i wylądował u sąsiada na drzewie. Czy ktoś miał coś takiego ? Jedynie szczęście takie, że straty nie są duże, a dron i kamera jest do naprawienia.

Polish - English translation
Parrot Disco - RTH error, automatic landing but without returning home ... Hello, ladies and gentlemen, and all lovers of Parrot Disco sky flights. I have flown many hours, but mainly on the original wi-fi, and only a few on LTE. And just a few days ago, what every drone pilot is afraid of happened to me. The drone stopped responding, stopped following commands and started landing by itself in a circular motion, but beware: not at home, not at the take-off site, but 200 meters from me. I lost control of it 200 meters away from me and it triggered the descent itself and landed at the neighbor's tree. Has anyone had something like this? Only luck is that the losses are not large, and the drone and the camera can be repaired.

**Comment by Robifpv20** [comment]
I would like to add that during the landing with a circular, circular motion, the camera image was not tilted, it was horizontal as during RTH. The difference is that the drone, instead of turning back, began to land immediately. All this happened during a gentle lowering of the flight and a slight turn. As if he was suddenly ordered to land in a remote place. The battery was over 4V per cell. Before this landing, the connection was very poor, it was not steered well. And the picture was sometimes tilted differently than I was turning ... I have a videoe screen recorder from this flight. It is very strange. The drone very often asks for recalibration after switching to 4G. I will also say that I like to fly with a 720P view and I had it set up then too. It was good only at the beginning, after a few minutes the image was still there, but the control was very delayed.

**Comment by Robifpv20** [comment]
...but the control was very delayed.

**Comment by ClassAxion** [comment]
Were you flying normally (manual) before losing range? You didn't do anything automatic like orbiting? Send us a video (you can upload on youtube as unpublic) that starts a few moments before the disco parrot loses signal.

**Comment by Robifpv20** [comment]
Ok. I will send you a movie recorded on a smartphone as unlisted, because this movie in the modem on the micro SD card is damaged and cannot be played. As for this flight, I was controlling it manually all the time. The last command to fly was probably the right stick towards myself, so I ordered him to fly up, because I noticed that he was starting to fly down, a moment earlier I performed a few commands to the left and right. As far as I remember, I did not give him the command to orbit and wait in the air, neither right nor left.

**Comment by ClassAxion** [comment]
You can try playing the damaged file in VLC: https://www.videolan.org/vlc/download-windows.pl.html

**Comment by Robifpv20** [comment]
please, here's a video from the phone:

https://youtu.be/5cKwQ5YcXaI

**Comment by ClassAxion** [comment]
It doesn't looks like RTH because you saw it on the app. I don't see any RTH messages and you don't get disconnected from the disco.

**Comment by s0ftice** [comment]
Two things, check if your issue is not the same as this https://github.com/uavpal/disco4g/issues/64

Secondly, circular landing on the spot (not at the take-off locations) happens only if the drone loses GPS signal, which almost never happens. Check that you have not placed anything on top of the front part of your CHUCK.

**Comment by Robifpv20** [comment]
> Nie wygląda jak RTH, ponieważ widziałeś to w aplikacji. Nie widzę żadnych komunikatów RTH i nie rozłączasz się z dyskoteką.

I'll call you later, I have to go to work. Let me just say it was very weird because the video was horizontal like RTH and I couldn't do anything even though I tried to lift it up as it taxied down.

**Comment by Robifpv20** [comment]
> Dwie rzeczy, sprawdź, czy Twój problem nie jest taki sam jak ten #64
> 
> Po drugie, lądowanie okrężne w miejscu (nie w miejscach startu) ma miejsce tylko wtedy, gdy dron traci sygnał GPS, co prawie nigdy się nie zdarza. Sprawdź, czy nie umieściłeś niczego na przedniej części uchwytu CHUCK.

That's how I read this whole thread with problem number 64. It is possible that Chuck crashed, blocked and did not want to execute commands, or the commands were so delayed that he was executing the previous commands from a few - a dozen or so seconds ago. As for the GPS, there is a Huawei modem above the CHUCK, glued to the cover and ends in front of the word Parrot. So I believe that the GPS is not obstructed.

**Comment by Robifpv20** [comment]
Please watch carefully from 6:45 am. I turn left and the image is tilted right, then I turn right and the image is left. It looks very unnatural that the camera is looking in a different direction than the direction of flight. As if I was giving the camera turn commands, not the drone. I was watching the camera all the time, but at the end it was as if I wasn't controlling it. As if the disco picked up some disturbance and obeyed the command, as in the flight plan. Forgive the blurry image, but after the last landing, the camera needs to be cranked up and focus. Can a blurry camera image affect flight?

**Comment by Robifpv20** [comment]
Here is a video of Wi-Fi flights, the image is only blurry at the beginning and then it improves halfway.  But that's not a problem, the camera's already cut, I can fix it.  What worries me the most is the emergency landing when using 4G, because nothing like that happened on Wi-Fi.

https://youtu.be/9bil25klJnY

**Comment by Robifpv20** [comment]
As a curiosity, I will tell you that in the garden of this gentleman where I landed Disco, there has been another drone for a month now, which also landed without returning home. Chinese version of the Mavic Pro - SG906 pro. Could someone have a signal jammer in this area, or something is emitting very high noise in this area? 
I already have a lot of flights in this area using wifi and there have never been problems. It's only the first time.

**Comment by Robifpv20** [comment]
I found the reason !!! there is a fault, won't you believe it?

**Comment by ClassAxion** [comment]
So what's the problem?

**Comment by Robifpv20** [comment]
The left servo mechanism is very hard to turn down. As if it was obliterated. You can pull it up and turn it, but it's really hard to go down. I don't know if it happened in flight or maybe from falling from a tree. After turning on the voltage, both servos seem to level, but when I am doing a flight simulation, the right servo works fine, and the left one only up and does not come back down anymore. If the servo overheated in flight, then we have the cause of the failure and automatic landing.

**Comment by ClassAxion** [comment]
It makes sense. Maybe these are fake emax servos?

**Comment by Robifpv20** [comment]
Zamieniłem wtyczki serwa lewego i prawego. Wszystko wskazuje na to że lewe serwo jest uszkodzone, ciezko chodzi. Po przesmarowaniu i dodaniu oliwy, jest lekka poprawa. Ale i tak lewe serwo się zacina. 99 % że powodem awarii była blokada serwa.

**Comment by ClassAxion** [comment]
Super! I was afraid that it was a software problem after all. 

I don't know if disco can diagnose servo failure like it does with motor failure (if so, an alert should pop up), however, looking at the video, I find that the C.H.U.C.K was trying to take control of the machine, so the image was similar to RTH. 

This was not a controller-initiated landing, the parrot just dropped by itself.

**Comment by Robifpv20** [comment]
I also believe Chuck has taken control and initiated an emergency landing.  Although you can see in the last seconds that I was adding gas and tried to raise Disco up.  I believe Chuck is checking the servos and detecting if any of them are sticking.  The right good servo when starting Disco makes one move to level, and the left bad servo makes two moves to be horizontal, first down and then back up.  During simulated take-off, the right servo moves up and down nicely, while the left servo only goes up and stops.  The Disco has an autopilot that supports it when the speed and roll is too low, so that it does not stall.  As in the final landing phase, we can steer left and right, but we can't go up and down anymore.  I also thought it was software or GPS fault, but luckily it's not Chuck's fault, but a broken servo.  And now very important !!!  Listen: I used these servos for 20 hours, and the previous owner said that I was 40 hours, which is 60 hours in total !!!  They should be replaced much earlier!  sorry for my poor english but i try my best to provide you with valuable information to fly safely and without crashing our favorite plane called Disco :)

**Comment by Robifpv20** [comment]
Please check if Pushbullet works in your free time. Because it doesn't work for me. I get an incomplete link, no traceability. Pushbullet only sends a link to the main Glympse website

**Comment by s0ftice** [comment]
see here: https://github.com/uavpal/disco4g/issues/88 (fix for Glympse)

**Comment by Robifpv20** [comment]
OK, thank you s0ftice. I will have to learn how to transfer files to Disco and replace that file.

**Comment by Robifpv20** [comment]
Everything is correct, the servo is broken and jams. I changed the servo plugs again and the left one stops after a while, when it stops, it stops working and stays in the down position, causing the drone to taxi to the right and the autopilot activates the automatic landing. Although the drone is in the starting position and CHUCK commands the ailerons up, the left one goes up and works for a short time. Later it goes down and is permanently locked in this position. I tried to push the aileron handle up, but I felt that the motor was working all the time and was holding it down, and the right aileron was still working properly and moving. I've also heard that it sometimes happens that the motor windings break where the silicone cables connect to the thin winding wires. Apparently, this winding breaks right next to the engine, so I put a small amount of glue under the cable and over the cable so that it does not move, so that it does not vibrate from vibrations and hard landings.

[url=https://postimg.cc/grDWH975][img]https://i.postimg.cc/grDWH975/IMG-20210616-154622.jpg[/img][/url]

**Comment by Telepilote** [comment]
In the video it looked like the disco went into a flat spin so the servo
fault makes lots of sense. 👍

**Comment by Robifpv20** [comment]
Servos replaced and adjusted. They work very well. Flight simulation done, everything indicates that the plane is ready to fly. A short test flight tomorrow, but only on wi-fi for now. When replacing the servo, pay attention to leveling and properly screw the aileron handles. If they are not equally even on both sides, if the left servo is higher and the right servo is lower, then maybe I got two right servos. You have to unscrew one servo and remove the main shaft with a rack, turn it 180 degrees and put it back. After this, both servos will stop at the same height.

**Comment by Robifpv20** [comment]
Today was the first test after the last crash, all systems are operational, the disco goes straight and soars up nicely, it's nice. It was a bit windy so I didn't go crazy too long, not too far. After 10 minutes, I landed gently, without comment. I guess all right, only now came my servo tester. I'll have fun with it tomorrow :)

**Comment by Telepilote** [comment]
---------- Forwarded message ---------
From: benjamin jones ***@***.***>
Date: Mon, 1 Nov 2021 at 18:43
Subject: Re: Invoice 1011 from Jones Conrete & Construction
To: Peter Hofland ***@***.***>


Thank you guys, have received.

Ben jones.
