### ISSUE TITLE
Parrot Disco - Fuse

### ISSUE THREAD

**Issue by Robifpv20** [uavpal/disco4g#97]
Welcome friends. Does anyone know what is the value of the main fuse F2 on the motherboard in CHUCK, located near the xt-60 power connector. My fuse has blown and I am looking for a replacement, but I do not know the value of this fuse.

**Comment by Robifpv20** [comment]
![Screenshot_2021-07-28-19-53-20-694_com android chrome](https://user-images.githubusercontent.com/85862141/127382326-417da75d-850b-4a11-a1a7-969b6fde2545.png)

**Comment by s0ftice** [comment]
That, not really a Disco4G topic. I remember this has been discussed before on Slack. Join us on https://uavpal.com/slack and post it in the channel #disco-general
